sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging-ci

install:

before_script:
  - docker-compose config
script:
  - docker-compose up -d
after_script:
  - docker images
  - docker ps
  - docker volume ls
notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
